@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(zootechnician, "Зоотехник", "Анализ текущего состояния скота, будущего объема мясной продукции")
Person(logistician, "Логист", "Планирование закупок")
Person(operator, "Оператор", "Получение уведомлений об инцидентах. Настройка расписания кормушек и поилок. Актуализация информации об остатках запасов еды")

System(platform, "Платформа мониторинга", "Центральная система мониторинга")
System(iam, "Система управления идентификацией и доступом", "Система управления идентификацией и доступом")
System(metrics, "Система мониторинга и сбора метрик", "Система мониторинга и сбора метрик")
System(local, "Локальная система мониторинга", "Локальная система мониторинга на ферме")

System_Ext(agrotech, "АгроПром Х - Цифровая платформа", "Основная цифровая платформа компании")
System_Ext(videoAnalytics, "Система видеоаналитики", "Система видеоаналитики на основе нейронных сетей, предоставленная партнерами")

Rel(zootechnician, platform, "Использует")
Rel(logistician, platform, "Использует")
Rel(operator, local, "Использует")
Rel_L(platform, agrotech, "Передает метрики")
Rel(local, videoAnalytics, "Передает видеопоток с камер")
Rel(videoAnalytics, local, "Передает события, обнаруженные в видеопотоке")
Rel_U(metrics, platform, "Собирает метрики")
Rel(platform, iam, "Использует для идентификации, аутентификации, авторизации пользователей")
Rel(local, iam, "Использует для идентификации, аутентификации, авторизации пользователей")
Rel_L(local, platform, "Передает данные о происходящем на ферме")

@enduml